import { useRef, useState, useCallback } from 'react';
import Uppy from '@uppy/core';
import AwsS3 from '@uppy/aws-s3';
import DashboardModal from '@uppy/react/dashboard-modal';
import '@uppy/core/dist/style.css';
import '@uppy/dashboard/dist/style.css';

/* ═══════════════════════════════════════════════════════════════
   MediaUpload — file upload via Uppy with direct-to-R2 upload.

   Uses Uppy (MIT) for all upload UI, progress, retry, and resumable
   uploads. The API server generates presigned URLs for R2 (S3-
   compatible). The browser uploads directly to R2 — no Worker CPU
   cost, no bandwidth through the API server.

   Custom code: ~2% (Uppy config + presign endpoint call).
   ═══════════════════════════════════════════════════════════════ */

interface MediaUploadProps {
  open: boolean;
  onClose: () => void;
  onUploaded?: (media: { key: string; contentType: string; kind: string; originalName: string }) => void;
}

function inferKind(contentType: string): 'photo' | 'document' | 'audio' | 'video' {
  if (contentType.startsWith('image/')) return 'photo';
  if (contentType.startsWith('audio/')) return 'audio';
  if (contentType.startsWith('video/')) return 'video';
  return 'document';
}

export default function MediaUpload({ open, onClose, onUploaded }: MediaUploadProps) {
  const [uppy] = useState(() => new Uppy({
    restrictions: {
      maxFileSize: 100 * 1024 * 1024, // 100MB
      allowedFileTypes: [
        // Images
        'image/*',
        // Documents
        '.pdf', '.docx', '.txt', '.md', '.odt', '.rtf',
        // Audio
        'audio/*',
        // Video
        'video/*',
      ],
    },
    autoProceed: false,
  }).use(AwsS3, {
    shouldUseMultipart: false,
    signRequest: async (req) => {
      // For PUT requests, we need to presign with the file's content type.
      // The key is already generated by the plugin (or we can use generateObjectKey).
      // We call our API to get a presigned URL for this key.
      const res = await fetch('/api/media/presign-key', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ key: req.key, method: req.method }),
      });
      if (!res.ok) throw new Error('Failed to get upload URL');
      const json = await res.json();
      return { url: json.data.uploadUrl };
    },
  }));

  const handleComplete = useCallback((result: any) => {
    if (result.successful && result.successful.length > 0) {
      for (const file of result.successful) {
        const key = file.s3Multipart?.key || file.awsS3?.key || file.name;
        onUploaded?.({
          key,
          contentType: file.type,
          kind: inferKind(file.type),
          originalName: file.name,
        });
      }
    }
  }, [onUploaded]);

  // Attach event listener once
  const attachedRef = useRef(false);
  if (!attachedRef.current) {
    uppy.on('complete', handleComplete);
    attachedRef.current = true;
  }

  return (
    <DashboardModal
      uppy={uppy}
      open={open}
      onRequestClose={onClose}
      proudlyDisplayPoweredByUppy={false}
      note="Images, PDFs, DOCX, audio, or video — up to 100MB"
      theme="dark"
    />
  );
}
